import Head from "next/head";
import styles from "src/styles/Home.module.css";
import { Footer } from "src/component/Footer/index";
import { Main } from "src/component/Main/Main";
import { Header } from "src/component/Header/Header";


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Indexpage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main page="index" />
      <Footer />
    </div>
  );
}
